### ISSUE TITLE
Light lag patch causes server to crash

### ISSUE THREAD

**Issue by b00p1** [cookiedragon234/PaperBin#16]
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at dev.binclub.paperbin.transformers.CustomLightingQueue.processQueue(LightUpdateRateLimiter.kt:200)
	at dev.binclub.paperbin.transformers.CustomLightingQueue.PROCESSNEIGHBOURQUEUE(LightUpdateRateLimiter.kt)
	at dev.binclub.paperbin.transformers.CustomLightingQueue.processUnload(LightUpdateRateLimiter.kt:235)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:397)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:354)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:309)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at dev.binclub.paperbin.transformers.CustomLightingQueue.processQueue(LightUpdateRateLimiter.kt:200)
	at dev.binclub.paperbin.transformers.CustomLightingQueue.PROCESSNEIGHBOURQUEUE(LightUpdateRateLimiter.kt)
	at dev.binclub.paperbin.transformers.CustomLightingQueue.processUnload(LightUpdateRateLimiter.kt:235)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:397)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:354)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:309)

Using ccspigot and paperbin

**Comment by x4e** [comment]
Fixed in 842d560
