### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nukerzz** [cookiedragon234/PaperBin#30]
root@ns524414:~/PaperAnarchy# java -Xmx1000m -Xms1000m -noverify -jar PaperBin.jar paper-1.12.2-1618\ \(1\).jar nogui
[paperbin INFO] Registering transformers...
[paperbin INFO] Make sure to enable queue-light-updates in paper config
[paperbin WARNING] WARNING: A fatal exception occured while initialising PaperBin 1.81

System Info:
   Title: OpenJDK 64-Bit Server VM
   Vendor: Private Build
   Version: 1.8.0_292
   RT Version: 1.8.0_292-8u292-b10-0ubuntu1~20.10-b10
   OS: Linux
   OS_V: 5.8.0-50-generic
   Arch: amd64
   JHome: /usr/lib/jvm/java-8-openjdk-amd64/jre
   Bukkit Version: null
   Bukkit Server Version: null
   Minecraft Version: null
[paperbin SEVERE]
java.lang.UnsatisfiedLinkError: dev.binclub.paperbin.native.NativeAccessor.registerClassLoadHook(Ldev/binclub/paperbin/native/PaperBinClassTransformer;)V
        at dev.binclub.paperbin.native.NativeAccessor.registerClassLoadHook(Native Method)
        at dev.binclub.paperbin.MainKt.main(Main.kt:28)

**Comment by dG9hc3Q** [comment]
Line 2:
>[paperbin INFO] Make sure to enable queue-light-updates in paper config

**Comment by Nukerzz** [comment]
it's already in true

**Comment by x4e** [comment]
Have you read the ReadMe?
